from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import os
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
chrome_driver_path = "C:\\Users\\Yashw\\OneDrive\\Selenium\\DJAR\\chromedriver.exe" # Replace with your actual path
driver = webdriver.Chrome()
driver.get("http://127.0.0.1:5500/index.html")
time.sleep(5)
driver.get("http://127.0.0.1:5500/why.html")
time.sleep(2)
driver.get("http://127.0.0.1:5500/index.html")
time.sleep(3)
driver.get("http://127.0.0.1:5500/sign-up2.html")
driver.find_element(By.ID,"name").send_keys("abcdef")
time.sleep(2)
driver.find_element(By.ID,"email").send_keys("abcdef@gmail.com")
time.sleep(2)
driver.find_element(By.ID,"password").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"cpass").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"phone").send_keys("7896541230")
time.sleep(2)
driver.find_element(By.ID,"submit").click()
time.sleep(2)
driver.get("http://127.0.0.1:5500/login2.html")
driver.find_element(By.ID,"email").send_keys("abcdef@gmail.com")
time.sleep(2)
driver.find_element(By.ID,"password").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"submit").click()
time.sleep(2)
driver.get("http://127.0.0.1:5500/index.html")
time.sleep(5)
driver.get("http://127.0.0.1:5500/sign-up.html")
driver.find_element(By.ID,"name").send_keys("abcdef")
time.sleep(2)
driver.find_element(By.ID,"email").send_keys("abcdef@gmail.com")
time.sleep(2)
driver.find_element(By.ID,"password").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"cpass").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"phone").send_keys("7896541230")
time.sleep(2)
driver.find_element(By.ID,"submit").click()
time.sleep(2)
driver.get("http://127.0.0.1:5500/login1.html")
driver.find_element(By.ID,"email").send_keys("abcdef@gmail.com")
time.sleep(2)
driver.find_element(By.ID,"password").send_keys("123456")
time.sleep(2)
driver.find_element(By.ID,"submit").click()
time.sleep(2)
driver.get("http://127.0.0.1:5500/trainer.html")
time.sleep(2)
driver.get("http://127.0.0.1:5500/contact.html")
driver.find_element(By.ID,"name").send_keys("abcdef")
time.sleep(2)
driver.find_element(By.ID,"email").send_keys("abcdef@gmail.com")
time.sleep(2)
driver.find_element(By.ID,"phone").send_keys("7896541230")
time.sleep(2)
driver.find_element(By.ID,"message").send_keys("lets build our path of success")
time.sleep(3)
driver.quit()